### ISSUE TITLE
Proxy for the Transalte API

### ISSUE THREAD

**Issue by ZyC0R3** [RitaBot-Project/RitaBot#101]
**Is your feature request related to a problem? Please describe.**
Google Translate has request limits. If too many requests are made, you can either end up with a 429 or a 503 error. You can use proxy to bypass them:

**Describe the solution you'd like**
Implementation of a proxy on the API Git, https://github.com/ZyC0R3/google-translate-api

**Describe alternatives you've considered**
Build it in to Rita, if possiable

**Comment by ArtanisTheOne** [comment]
Check out [this example](https://github.com/vkedwardli/google-translate-api#proxy) of a proxy being used when making requests using tunnel.

**Comment by ZyC0R3** [comment]
Will revisit, not needed for the moment
