### ISSUE TITLE
Events.js - Bot Trigger Command Variable 

### ISSUE THREAD

**Issue by ZyC0R3** [RitaBot-Project/RitaBot#106]
**Start Line**  
Events.js Line 35 & 36

**Code**
```
         translateCmd: "!translate",
         translateCmdShort: "!t",
```

Can the command structure be changed to somthing other than !t if the user wants it to be changed, Like in channel can a user type !t command and get prompted to change the command trigger from !t. 

By the looks of it this would auto update 
```
   const statusMap =
   {
      "online": function()
      {
         bot.setPresence({
            status: "online",
            game: {
               name: config.translateCmdShort + " help / " + config.translateCmd +" help - V." + config.version
            }
         });
      },
```

**Comment by JShep89** [comment]
exports.run = (client, message, args) => {
  const modRole = message.guild.roles.find ("name", "Discord Admin");
  if (! modRole)
    return console.log ("The Discord Admin role does not exist.");

  if (! message.member.roles.has (modRole.id))
    return message.reply ("You can't use this command.");

   // Changes the prefix of the command (eg "! Prefix +" receives the "+" so it becomes "+ prefix").
      let newPrefix = message.content.split ("") .slice (1, 2) [0];
      // Changes the configuration in memory
      config.prefix = newPrefix;
      // Saves the file.
      fs.writeFile ("./ config.json", JSON.stringify (config), (err) => console.error);
}

**Comment by JShep89** [comment]
Command added
