### ISSUE TITLE
Auto Language Detection. 

### ISSUE THREAD

**Issue by ZyC0R3** [RitaBot-Project/RitaBot#122]
**Describe the bug**
The bot will not use the Auto Tag as a valid langauge. 

**To Reproduce**
!t channel from auto to en for #chan

**Expected behaviour**
Detect and accept Auto as a valid langauge 

**Error Message from Webhook**
Please specify a valid language to translate from.

**Screenshots**
![image](https://user-images.githubusercontent.com/39091558/80537804-87889480-899c-11ea-9d27-d487e429a58f.png)

**Additional context**
Code location can be found in:

Core > Transalte.js Line 171
Core > lang.check.js Line 76
Commands > transalte.auto.js Line 29

**Comment by JShep89** [comment]
Artanis for the win
