### ISSUE TITLE
db Error with dbfix command. 

### ISSUE THREAD

**Issue by ZyC0R3** [RitaBot-Project/RitaBot#157]
**Is your feature request related to a problem? Please describe.**
db errors are given with dbfix command, however these are not accurate.
Search "reply" name not updated if server is renamed.

**Describe the solution you'd like**
Suppress, remove or fix. 
Update name value in DB

**Comment by ArtanisTheOne** [comment]
Querying `INSERT IGNORE` should fix this error, or prevent it. Prevents adding values to places which already have a value
