### ISSUE TITLE
DM Translations broken

### ISSUE THREAD

**Issue by ZyC0R3** [RitaBot-Project/RitaBot#182]
**Describe the bug**
when a chan is DM translating to multiple languages it will pick the last lanage in the DB of the languages are different from each other.

**To Reproduce**
1. Go to and channel
2. Type !t channel from english to de for @user
3. Type !t channel from english to fr for @user
4. All translations will be sent in the last language, so in this case french. 

**Expected behaviour**
Each translation should be in its own language

**Additional context**
Error and bug known in master and test branch. 

As this bug has been present in multi branches this has a target fix for 1.3.0

**Comment by uniktron** [comment]
![0F9DF4D9-0C37-40C7-8C0F-AB365AF82233](https://user-images.githubusercontent.com/78520257/107890911-7d169780-6ee9-11eb-9164-3c847f7699df.jpeg)

> I’m experiencing this error on my end. It was working fine until today. I restarted the repo and did a new pull. I still getting the error message like on my screenshot. DM/ User Translation Function Disabled. Anyone know if there a fix? I’m using version 1.2.1-9.

**Comment by ArtanisTheOne** [comment]
@uniktron 

> ![0F9DF4D9-0C37-40C7-8C0F-AB365AF82233](https://user-images.githubusercontent.com/78520257/107890911-7d169780-6ee9-11eb-9164-3c847f7699df.jpeg)
> 
> > I’m experiencing this error on my end. It was working fine until today. I restarted the repo and did a new pull. I still getting the error message like on my screenshot. DM/ User Translation Function Disabled. Anyone know if there a fix? I’m using version 1.2.1-9.

The correct format is `!t channel from en to es for #targetchannel`
So if you want the same channel ping the channel, a channel ping is needed or else it will think you are trying to setup a personal user PM translation

**Comment by uniktron** [comment]
Did that as well and still not working. Same error message.

**Comment by ArtanisTheOne** [comment]
Can you send what you sent for the command here?

**Comment by ArtanisTheOne** [comment]
@uniktron Just wanted to follow up. Would you mind joining our discord for me to help you ?[re fluently?

**Comment by drdunn858** [comment]
I have the same issue.  I have a single user who speaks spanish and I have the channel set to !t channel to english from spanish for #channel however for him I need to have !t channel to spanish from english for @user however, I get the above error screen that it is disabled is there a work around other than making two channels and having the translate into each other?

**Comment by ArtanisTheOne** [comment]
@drdunn858

**Comment by drdunn858** [comment]
Okay, for the time being I will simply create different channels for each language needed and redirect translations accordingly.  Thanks.

**Comment by ArtanisTheOne** [comment]
Sorry I couldnt help more, in the future this will be fixed. We are planning to rebuild it all

**Comment by drdunn858** [comment]
Thank you again, I am really impressed with the ease of using this.
