### ISSUE TITLE
Ping users across translation channel (not embedded messages)

### ISSUE THREAD

**Issue by helmchen-oO** [RitaBot-Project/RitaBot#246]
Situation:

To reduce language channels seen by members, it would be a cool feature to write in your native language channel, but ping people in different language channels. 
Goal: "en"-speaker gets his ping in "en"-channel sent from "de"-channel with a not embedded message, while he can't see de-channel. 

1. it looks like the user1 in "de"-channels writes directly to en-user (user2) in en-channel.
2. only one ping for en-user
3. a lot less channels, as admin can add language roles to remove unnecessary languages for people.

Example:
user 1 is German, so he gets role DE and only see DE-channels
user 2 is English, so he gets role EN and only see EN-channels

user 1 writes in German in DE-channel and pings user2 (@user2)
user 2 will get a ping with translated message in EN-channel, but doesn't see the message in DE-channel.

Problem. If you ping someone via its nickname in DE-Channel who can't see that de-channel, he gets no ping in EN-Channel, as discord can't find the nickname of user2 in DE-Channel. BUT you can use the real name (name#xxxx). Discord is then able to transport the ping to en-channel. For user1 it looks like user2 is also in DE-Channel. As people don't really know the real names (name#xxxx), the bot would need to check the real name (e.g. Helm#xxxx), if a user uses the nickname (e.g. Helm)

This way, conversation across language channels look natural, as messages are not embedded and it looks like both write in same channel. We can reduce language channels seen by people and they do not loose the ping feature.

I hope you understand it :D 
cheers & Thanks Helm.

**Comment by ArtanisTheOne** [comment]
Hmmm, I'm not sure how this would be implemented since this can be done. My 112 server has this setup with lamgauge roles so people see a max of 4 translation channels in their language.

Pings do go across but since a DE user isnt in the EN channels you cant really ping them unless you use their ID since with the name#discrimnator method the translator adds a space making it @ name#discriminator or @name#discriminator so it doesnt function.

**Comment by ArtanisTheOne** [comment]
We implement a webhook/user pinger so if you ping the webhook name (click on the webhook author name) it searches for users with that name and pings them in the translation channels.

**Comment by ZyC0R3** [comment]
This is not something we will abe able to do for the moment, but we will revisit it in the future.
