### ISSUE TITLE
@ mentions getting clobbered in JP and CN.

### ISSUE THREAD

**Issue by horknfbr** [RitaBot-Project/RitaBot#272]
**Describe the bug**
"@" mentions are getting translated then the dest language is Japanese or Chinese (seems to be a bit random and users are most of the time rendered correctly

**To Reproduce**
1. setup two channels to translate to each other using Japanese or, Chinese as the destination from English
2. send an "@" mention to a user or group from the English channel
3. the "@" mention in the JP, CN will be the id, not the name of the group/user, but mangled enough that discord cant process it ex. ```@Member -> <@726588059147305061>``` this is EN -> CN

**Expected behaviour**
the "@" mention will be ignored for translation and come across in the correct format for discord to process as it is when translating from EN -> ES

**Error Message from Webhook**
none

**Screenshots**
the text from "doupepe" is originally from the Spanish channel, the text from "Kedamder" is from the English channel
English:
![EN channel](https://i.imgur.com/wdD7Fi8.png)
Japanese:
![JP channel](https://i.imgur.com/h5ZQCJT.png)

**Additional context**
the "@" mentions work on my server in languages EN, ES, RU, TR, VI, and TH

**Comment by ArtanisTheOne** [comment]
Ah yes, I assume this is because we have not found a way to tell the translator not to translate a word in the string we pass to it. The error is instead of being <@&ROLEID> it's removing the & making it a user ping for a user that doesnt exist. I'll look into this

**Comment by ArtanisTheOne** [comment]
Fixed with 1.2.2-6 😄
