### ISSUE TITLE
Make RITA translate old messages

### ISSUE THREAD

**Issue by Remurr** [RitaBot-Project/RitaBot#275]
It seems that Rita doesn't want to translate messages (with flag reactions) that was sent before she got plugged in to the server? Only new messages. This also happens when she stops working.

**Describe the solution you'd like**
I expect it to translate any message.

**Additional context**
Demo:
https://www.youtube.com/watch?v=TUSTLN80Kq8

**Comment by ArtanisTheOne** [comment]
*Note*: this is due to the way Discord.js caches messages. It has difficulty collecting messages and message reactions from messages not in the cache (ones not sent in the time the bot was online)
