### ISSUE TITLE
No spaces between words when translating from Russian to Ukrainian and reverse

### ISSUE THREAD

**Issue by MqtUA** [RitaBot-Project/RitaBot#291]
**Describe the bug**
No spaces between words when translating from Russian to Ukrainian and reverse. Happens both with flag interaction and by using command. Everything works fine when translating from English to Ukrainian/Russian.

**Screenshots**
![Rita_ru-ua_bug](https://user-images.githubusercontent.com/26764029/113178431-3f7e8b80-9257-11eb-9ad7-0f9a7745cadd.png)

**Comment by ArtanisTheOne** [comment]
This has been since fixed with the translation api change, but this could arise in the future. Stay tuned for 1.2.2-6 for the fix
