### ISSUE TITLE
RitaBot requires Administrator permissions

### ISSUE THREAD

**Issue by ddugovic** [RitaBot-Project/RitaBot#401]
**Describe the bug**
Either I don't understand Discord integration permissions, or RitaBot refuses to write in channels unless it has Administrator permissions?

**To Reproduce**
1. Invite RitaBot via https://top.gg/bot/827301865539764284 but modify "permissions=8" to "permissions=2048" (Text Permissions > Send Messages)
2. Observe RitaBot writing a message:
![image](https://user-images.githubusercontent.com/1834123/122035096-c2fc4300-cd97-11eb-8936-482dbeef20f9.png)
3. Respond with !tr help
4. Observe RitaBot fail to respond but send a PM instead

**Expected behaviour**
RitaBot communicates in the same channel we were already communicating in

**Error Message from Webhook**
What?

**Screenshots**
![image](https://user-images.githubusercontent.com/1834123/122035246-e626f280-cd97-11eb-9698-ec1febf6d2db.png)

**Additional context**
![image](https://user-images.githubusercontent.com/1834123/122035414-0f478300-cd98-11eb-956e-de2b835e5bd1.png)

**Comment by ArtanisTheOne** [comment]
She requires embed links & managwe webhooks

**Comment by ArtanisTheOne** [comment]
The reason it seems she is unresponsive is most likely because it isnt able to send the message as an embed (which all commands are in). For example, that welcome message should include an embed message with it but it does not, making me think perhaps you didnt give her enough permissions to send embed messages

**Comment by ZyC0R3** [comment]
Please run this command and share the results
`!tr checkperms bot`

This will give you a result of permissions that RITA needs to have to function at 100%

**Comment by ddugovic** [comment]
Thanks; I added permissions:
![image](https://user-images.githubusercontent.com/1834123/122053258-36a84b00-cdac-11eb-8969-599c5e487fa3.png)

Incidentally `!tr checkperms bot` causes this response:
> RITA does not have permission to write in your server Tadpole Pond. Please fix.

I see RITA recommends I join the support server for further support; she did just respond in my general channel but then left, so I suppose I'll pursue whatever next through the support server.

**Comment by ZyC0R3** [comment]
Not a problem, message me in discord and I can take a look for you.

**Comment by KorewaLidesu** [comment]
Make sure to allow View channel to bot, else it won't be able to see it.
