### ISSUE TITLE
Consideration of similar flags

### ISSUE THREAD

**Issue by Steppenwolf443** [RitaBot-Project/RitaBot#422]
**Is your feature request related to a problem? Please describe.**
In Discord, some flags are very similar but some are translated and some are not. On the smartphone, we don't see any difference when we react.

**Describe the solution you'd like**
Translate with the both flags who looks alike

**Describe alternatives you've considered**
?

**Additional context**
The main flags I saw are :flag_ea: (looks like the spanish flag) and :flag_cp: (looks like the french flag)

**Comment by ZyC0R3** [comment]
This is not something we will abe able to do for the moment, but we will revisit it in the future.
