### ISSUE TITLE
Strip mentions from cross channel translations

### ISSUE THREAD

**Issue by pir8radio** [RitaBot-Project/RitaBot#435]
**Is your feature request related to a problem? Please describe.**
not really a "problem"  but I have a main "general chat" channel that is EN, then a few other channels ZH, ES, DE etc...   When someone @mentions someone in either the general or one of the languages it transfers over to all other channels. I understand with roles I can limit this.

**Describe the solution you'd like**
It would be nice to have a bot setting to "strip" @mentions from translations automatically, so they are only actually mentioned in the channel the user originally mentioned a user.   This would allow me to not have to create special roles for everyone and manage that..   if they get a mention in the ZH channel they know to go to their language to read it. 

**Describe alternatives you've considered**
considered roles, but its another thing I would have to manage..   

**Additional context**
thank you for considering.

**Comment by ArtanisTheOne** [comment]
* **Note for myself** 
    * Store in db like other values, go through another step in message.js to change mentions at the root
    
  
Just wondering; Is having the name of the pinged user important to you or just stripping mentions? Replacing a ping with a username may take a bit more processing power

**Comment by JShep89** [comment]
This issue will be solved with the code that's being added to strip the pings of the everyone and here tags

**Comment by pir8radio** [comment]
> * **Note for myself**
>   
>   * Store in db like other values, go through another step in message.js to change mentions at the root
> 
> Just wondering; Is having the name of the pinged user important to you or just stripping mentions? Replacing a ping with a username may take a bit more processing power

sorry just saw this..  that's a good point.. if not to difficult i think  taking   @Pir8radio and converting it to Pir8radio would be cool..

**Comment by JShep89** [comment]
Closing this issue and tying it in with the everyone and here mention toggle
