### ISSUE TITLE
Same channel image/gif/emoji

### ISSUE THREAD

**Issue by JShep89** [RitaBot-Project/RitaBot#459]
**Is your feature request related to a problem? Please describe.**
Same channel translation posting images, gifs and emojis

**Describe the solution you'd like**
ignore images, gifs and emojis if dest = origin

**Comment by ZyC0R3** [comment]
Same chan Translation, Regardless of language. 

- [x] Images 
- [x] Gif
- [ ] Emoji

**Comment by ZyC0R3** [comment]
Added with [705eb30](https://github.com/RitaBot-Project/RitaBot/commit/705eb306adc33774865a047015017958325da781)

https://github.com/RitaBot-Project/RitaBot/blob/705eb306adc33774865a047015017958325da781/src/core/send.js#L409-L423

https://github.com/RitaBot-Project/RitaBot/blob/705eb306adc33774865a047015017958325da781/src/core/send.js#L472-L486

https://github.com/RitaBot-Project/RitaBot/blob/705eb306adc33774865a047015017958325da781/src/core/send.js#L731-L737

https://github.com/RitaBot-Project/RitaBot/blob/705eb306adc33774865a047015017958325da781/src/core/send.js#L741-L748

**Comment by JShep89** [comment]
closing this issue and adding the remaining task to the to do list
