### ISSUE TITLE
Automatic deleted messages of banned member

### ISSUE THREAD

**Issue by Trainer-Paul** [RitaBot-Project/RitaBot#462]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] A player is banned or posts bad comments that have to be deleted manually.

**Describe the solution you'd like**
A clear and concise description of what you want to happen. When banned automatically delete messages, or a way to tag the messages for deleting in all Language channels.

**Describe alternatives you've considered**
An emoji on the post to delete any remaining posts thought the server.

**Additional context**

**Comment by JShep89** [comment]
If we can figure this out it would be a step in the right direction for retranslating edited messages

**Comment by ZyC0R3** [comment]
> > If we can figure this out it would be a step in the right direction for retranslating edited messages
> 
> bots can't delete messages over 30 days old, at least no bot that uses !purge commands can

You can do, but most bots dont or wont cache message over 30 days due to mem limits, RITA caches no messages for this very reason, but we may be able to search by user id, i can look in to it.
