### ISSUE TITLE
Display the source language of an auto translated message

### ISSUE THREAD

**Issue by reddeath68** [RitaBot-Project/RitaBot#465]
Basically what the title says, when a message is translated with the auto feature can it say what the original language was?

**Comment by ZyC0R3** [comment]
Added with [705eb30](https://github.com/RitaBot-Project/RitaBot/commit/705eb306adc33774865a047015017958325da781)

https://github.com/RitaBot-Project/RitaBot/blob/705eb306adc33774865a047015017958325da781/src/core/translate.js#L643-L648
