### ISSUE TITLE
RitaBot replying with source language and translation sometimes

### ISSUE THREAD

**Issue by lckystr81** [RitaBot-Project/RitaBot#466]
**Describe the bug**
I have RitaBot set to auto translate English to Japanese and Japanese to English. Every once in a while RitaBot is replying with English and Japanese translation when source text is English. It doesn't happen every time but randomly.

**To Reproduce**
1. Type in english in the channel

**Expected behaviour**
Japanese translation as the reply

**Error Message from Webhook**
No error message

**Screenshots**
![3](https://user-images.githubusercontent.com/49419181/137412860-bbe1caea-7f53-4002-82af-62dd427b397c.jpg)
![1](https://user-images.githubusercontent.com/49419181/137412861-bb1cafc6-c034-44c9-bfce-5c8f76d0305a.jpg)
![2](https://user-images.githubusercontent.com/49419181/137412864-9fe46f49-a850-4a0f-ae4c-7dc19c18e0cb.jpg)
.

**Comment by ZyC0R3** [comment]
Should be fixed with [705eb30](https://github.com/RitaBot-Project/RitaBot/commit/705eb306adc33774865a047015017958325da781)
