### ISSUE TITLE
same channel per-user translation feature like smoogle translate

### ISSUE THREAD

**Issue by igotadell** [RitaBot-Project/RitaBot#469]
**Is your feature request related to a problem? Please describe.**
not a problem but this is a feature many are using in smoogle and some other bots including that hentai bot that does translation

**Describe the solution you'd like**
in smoogle, if you type "?tr en to ru for me" in a channel, she will repeat your messages in russian until disabled
I'd like that functionality

**Describe alternatives you've considered**
smoogle, that hentai bot, others have it.

**Additional context**
you know I love you guys

**Comment by ZyC0R3** [comment]
This is not something we will abe able to do for the moment, but we will revisit it in the future.
