### ISSUE TITLE
Suggesting feature : Custom emoji sends custom set of language translations

### ISSUE THREAD

**Issue by LaSauceBolo** [RitaBot-Project/RitaBot#470]
**Is your feature request related to a problem? Please describe.**
We are using RITA bot for translating messages on the discord of our in-game alliance, and we have several languages spoken by different people, and they don't all understand each other, so usually we would have 3 or 4 reactions to each messages for translating.

**Describe the solution you'd like**
A way to add a custom emoji that will make the bot translate the message into a customized set of languages. For example I would react with the emoji :french_bread: and get a translation in French, Spanish and English. 

**Describe alternatives you've considered**
blank

**Additional context**
blank

**Comment by ZyC0R3** [comment]
This is not something we will abe able to do for the moment, but we will revisit it in the future.
