### ISSUE TITLE
Embed Off Language marker. 

### ISSUE THREAD

**Issue by Trainer-Paul** [RitaBot-Project/RitaBot#471]
With embed off it's hard to tell what language was spoken if using flag reactions, of where the original text was sent from if using a cross channel set up. 
The answer is:
Add the 2 letter language code somewhere in the name, or at the beginning or end of the txt messages. 
Like (en) 
This will let the administrator know what language this is - or and idea where the original message channel is for this message. 
Thanks for your hard work and dedication.

**Comment by ZyC0R3** [comment]
Added with [705eb30](https://github.com/RitaBot-Project/RitaBot/commit/705eb306adc33774865a047015017958325da781)

https://github.com/RitaBot-Project/RitaBot/blob/705eb306adc33774865a047015017958325da781/src/core/translate.js#L643-L648

**Comment by JShep89** [comment]
@ZyC0R3 this one was for with embed off, your fix above was for embed on

**Comment by ZyC0R3** [comment]
Ow yea. Will look in to adding that in.

**Comment by ZyC0R3** [comment]
Added
