### ISSUE TITLE
Destination of reaction translations

### ISSUE THREAD

**Issue by ZyC0R3** [RitaBot-Project/RitaBot#486]
add settings command to set destination of reaction translations

**Comment by ZyC0R3** [comment]
The likelihood of is minimal. As there are too many possibilities it can be abused. But I will investigate it and see

**Comment by JShep89** [comment]
> The likelihood of is minimal. As there are too many possibilities it can be abused. But I will investigate it and see

I have received numerous requests for the ability to have Reaction translations sent to the requester via DM
