### ISSUE TITLE
Profanity filter

### ISSUE THREAD

**Issue by ZyC0R3** [RitaBot-Project/RitaBot#492]
The command structure

- [ ] !tr profanity [off/replace/delete]
  - General toggle command.

- [ ] !tr profanity [add/remove] {Lang} {word1, word2}
  - Add or remove words to a language set.

- [ ] !tr profanity list {Lang}
  - Generate a list of word in the chosen language. 

- [ ] !tr profanity whitelist [role/user/channel] {ID}
  - Whitelist a user, role or channel from profanity filtering

- [ ] !tr profanity reset
  - Reset or settings associated with profanity filter.

**Comment by ZyC0R3** [comment]
Settings variable has been added. 
Profanity.js has been created
Replace Function preliminary testing works.

**Comment by JShep89** [comment]
changed command name to profanity in settings.js
