### ISSUE TITLE
ClientOptions: WaitGuildTimeout

### ISSUE THREAD

**Issue by ZyC0R3** [RitaBot-Project/RitaBot#503]
Add new client option

https://github.com/discordjs/discord.js/blob/2bfc638a5cd0e4c0b2e69971d30828b51ab3c563/typings/index.d.ts

Line 4007

**Comment by ZyC0R3** [comment]
It's now defualted to 15 seconds. But we should change this to 7 ish. See if it reduces load time.

**Comment by JShep89** [comment]
not sure how we would test this one

**Comment by JShep89** [comment]
I added the option and set it to 7 seconds, but am unsure of how to test it.
