### ISSUE TITLE
Fix same language check for short response

### ISSUE THREAD

**Issue by JShep89** [RitaBot-Project/RitaBot#519]

**Comment by JShep89** [comment]
![image](https://user-images.githubusercontent.com/46389911/151271400-29e70ecc-cbab-4532-8379-56a5ee9e90cb.png)

**Comment by JShep89** [comment]
When the bug happens:
detectedLang is "auto"
channelFrom is "auto"
Neither those 2 return conditions will return true then

**Comment by JShep89** [comment]
![image](https://user-images.githubusercontent.com/46389911/151271820-2cf24dcf-34b6-42ad-8845-e492665ddc9d.png)

**Comment by JShep89** [comment]
![image](https://user-images.githubusercontent.com/46389911/151278276-008f693c-221f-4ee3-8013-bcfa6a768775.png)

**Comment by cyberlooper** [comment]
`const detlang = detect(matches.text);
      try
      {

         if (detlang === opts.to)
         {

            logger("debugerror", `Command Message Deleted Error, announce.js = Line 40`);
            return;

         }

      }
      catch (err)
      {

         logger("debug", `DEBUG: Something has gone wrong.`);

      }`

Issue resolved by language detection before passing to Google.
