### ISSUE TITLE
Cooldown for DM translations and Commands

### ISSUE THREAD

**Issue by wdaniel1985** [RitaBot-Project/RitaBot#83]
**Is your feature request related to a problem? Please describe.**
My bot got recently spammed with dm translations. Due to the spamming, the bot stopped working

**Describe the solution you'd like**
Timeout for dm translations and for executing commands in a channel

**Describe alternatives you've considered**
Currently, dm with the bot are deactivated on my branch

**Additional context**
The guid in https://discordjs.guide/command-handling/adding-features.html#cooldowns gives a nice description how to handle such spamming.

**Comment by ZyC0R3** [comment]
DM transaltion disabled untill further notice
